//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationIolitaTeamWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public int MadelId { get; set; }
        public string UserId { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Model Model { get; set; }
        public virtual ICollection<Record> Records { get; set; }
    }
}
