//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationIolitaTeamWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<float> Distance { get; set; }
        public Nullable<float> Quantity { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
